<a href="https://colab.research.google.com/github/anshatwork-007/Study-of-Numpy/blob/main/Experiment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Name: Ansh Yadav
# Branch: ENTC
# Batch: 2025-29
# Experiment 8

## Title: Tools for EDA - Numpy


In [8]:
# Short name of numpy can be np
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [13]:
a.ndim

1

In [11]:
b.ndim

2

In [14]:
a.shape

(4,)

In [15]:
b.shape

(2, 3)

In [16]:
a.dtype

dtype('int64')

In [17]:
b.dtype

dtype('int64')

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.eye((4)) # gives diagonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [30]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
c=a + 5
d=a * 2
print(c)
print(d)

[15 25 35 45]
[20 40 60 80]


In [37]:
np.mean(a)

np.float64(25.0)

In [39]:
np.max(a)

np.int64(40)

In [40]:
np.median(a)

np.float64(25.0)

In [41]:
np.min(a)

np.int64(10)

In [42]:
np.sum(a)

np.int64(100)